services:
  - type: web
    name: visual-search
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.16