name: Keep Pinecone Index Alive

on:
  schedule:
    # Run every 5 days at 2 AM UTC
    - cron: '0 2 */5 * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  ping-index:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install pinecone
    
    - name: Ping Pinecone Index
      env:
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      run: |
        python -c "
        from pinecone import Pinecone
        import os
        
        pc = Pinecone(
            api_key=os.environ['PINECONE_API_KEY'],
        )
      
        index = pc.Index('multi-project-index')
        stats = index.describe_index_stats()
        print(f'Index active with {stats.total_vector_count} vectors')
        "